# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ""
    org_name: ""
    description: "Stefano Persano Adorno - Personal Website"
    twitter: ""
  analytics:
    google_analytics: ""
    baidu_tongji: ""
    plausible: ""
    fathom: ""
    pirsch: ""
  verification:
    google: ""
    baidu: ""

# Site header
header:
  navbar:
    enable: true
    blox: floating-theme-toggler

# Site footer
footer:
  copyright:
    notice: "© {year} Stefano Persano Adorno. All rights reserved."
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: "Jan 2, 2024"
  time_format: "3:04 PM"

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: true
